# Generated by Django 6.0.6 on 2026-06-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaVeterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=120, verbose_name='Nombre de la mascota')),
                ('nombre_dueno', models.CharField(max_length=120, verbose_name='Nombre del dueño')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('tipo_mascota', models.CharField(max_length=50, verbose_name='Tipo de mascota')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de cita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cita Veterinaria',
                'verbose_name_plural': 'Citas Veterinarias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
